# Generated by Django 5.2.5 on 2025-09-10 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_color_talle_remove_product_variant_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
