# Generated by Django 5.2.5 on 2025-09-10 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
