# Generated by Django 5.2.5 on 2025-10-16 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=255, verbose_name='URL de la imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto alternativo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen del producto',
                'verbose_name_plural': 'Imágenes del producto',
                'ordering': ['order', 'id'],
            },
        ),
    ]
