# Generated by Django 5.2.5 on 2025-09-11 00:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=255, verbose_name='Nombre del cliente')),
                ('cliente_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto')),
                ('metodo_envio', models.CharField(choices=[('olmos', 'Retiro en Patio Olmos (Miércoles 17:15 hs)'), ('cadete', 'Envío por cadete Uber (pago previo)'), ('domicilio', 'Retiro por mi domicilio (horario a coordinar)'), ('plaza', 'Plaza Rivadavia (fines de semana 16 a 20 hs)')], max_length=20)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20)),
                ('opcion_entrega', models.CharField(blank=True, choices=[('ahora', 'Lo antes posible'), ('hoy', 'Hoy a tal hora'), ('mañana', 'Mañana a tal hora'), ('fecha', 'En una fecha específica')], max_length=20, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('completado', models.BooleanField(default=False)),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='cart.cart')),
            ],
        ),
    ]
